# Generated by cucumber-sinatra. (2014-07-29 17:05:59 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/dead_cockroach.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = DeadCockroach

class DeadCockroachWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  DeadCockroachWorld.new
end
