language: ruby
rvm:
- 2.4.0
deploy:
  provider: heroku
  api_key:
    secure: fUaANEjIEvQNGnRjLcEjMz5GmrB86EehuUth3PWWt7nwU6it/MF3tj30LsM6dXFdBc5yaLB4GY5LLJRSuVM8OZSG9JFjLQgQUYBkjVgWBO+k+8kX6iT90z9klzWUudo4UjNZFEa73+XQiUtDPDDW3lnWwwxPSWjgFiWjMSkPawo=
  app: dead-cockroach
  on:
    repo: pikesley/dead-cockroach
